package org.antczak.hadoop.holidays;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by krr on 11.08.14.
 */
public class Countries {
    public static List<String> names = new ArrayList<String>();

    static {
        names.add("Afghanistan");
        names.add("Akrotiri");
        names.add("Albania");
        names.add("Algeria");
        names.add("American Samoa");
        names.add("Andorra");
        names.add("Angola");
        names.add("Anguilla");
        names.add("Antarctica");
        names.add("Antigua and Barbuda");
        names.add("Argentina");
        names.add("Armenia");
        names.add("Aruba");
        names.add("Ashmore and Cartier Islands");
        names.add("Australia");
        names.add("Austria");
        names.add("Azerbaijan");
        names.add("Bahamas, The");
        names.add("Bahrain");
        names.add("Bangladesh");
        names.add("Barbados");
        names.add("Bassas da India");
        names.add("Belarus");
        names.add("Belgium");
        names.add("Belize");
        names.add("Benin");
        names.add("Bermuda");
        names.add("Bhutan");
        names.add("Bolivia");
        names.add("Bosnia and Herzegovina");
        names.add("Botswana");
        names.add("Bouvet Island");
        names.add("Brazil");
        names.add("British Indian Ocean Territory");
        names.add("British Virgin Islands");
        names.add("Brunei");
        names.add("Bulgaria");
        names.add("Burkina Faso");
        names.add("Burma");
        names.add("Burundi");
        names.add("Cambodia");
        names.add("Cameroon");
        names.add("Canada");
        names.add("Cape Verde");
        names.add("Cayman Islands");
        names.add("Central African Republic");
        names.add("Chad");
        names.add("Chile");
        names.add("China");
        names.add("Christmas Island");
        names.add("Clipperton Island");
        names.add("Cocos (Keeling) Islands");
        names.add("Colombia");
        names.add("Comoros");
        names.add("Congo, Democratic Republic of the");
        names.add("Congo, Republic of the");
        names.add("Cook Islands");
        names.add("Coral Sea Islands");
        names.add("Costa Rica");
        names.add("Cote d'Ivoire");
        names.add("Croatia");
        names.add("Cuba");
        names.add("Cyprus");
        names.add("Czech Republic");
        names.add("Denmark");
        names.add("Dhekelia");
        names.add("Djibouti");
        names.add("Dominica");
        names.add("Dominican Republic");
        names.add("Ecuador");
        names.add("Egypt");
        names.add("El Salvador");
        names.add("Equatorial Guinea");
        names.add("Eritrea");
        names.add("Estonia");
        names.add("Ethiopia");
        names.add("Europa Island");
        names.add("Falkland Islands (Islas Malvinas)");
        names.add("Faroe Islands");
        names.add("Fiji");
        names.add("Finland");
        names.add("France");
        names.add("French Guiana");
        names.add("French Polynesia");
        names.add("French Southern and Antarctic Lands");
        names.add("Gabon");
        names.add("Gambia, The");
        names.add("Gaza Strip");
        names.add("Georgia");
        names.add("Germany");
        names.add("Ghana");
        names.add("Gibraltar");
        names.add("Glorioso Islands");
        names.add("Greece");
        names.add("Greenland");
        names.add("Grenada");
        names.add("Guadeloupe");
        names.add("Guam");
        names.add("Guatemala");
        names.add("Guernsey");
        names.add("Guinea");
        names.add("Guinea-Bissau");
        names.add("Guyana");
        names.add("Haiti");
        names.add("Heard Island and McDonald Islands");
        names.add("Holy See (Vatican City)");
        names.add("Honduras");
        names.add("Hong Kong");
        names.add("Hungary");
        names.add("Iceland");
        names.add("India");
        names.add("Indonesia");
        names.add("Iran");
        names.add("Iraq");
        names.add("Ireland");
        names.add("Isle of Man");
        names.add("Israel");
        names.add("Italy");
        names.add("Jamaica");
        names.add("Jan Mayen");
        names.add("Japan");
        names.add("Jersey");
        names.add("Jordan");
        names.add("Juan de Nova Island");
        names.add("Kazakhstan");
        names.add("Kenya");
        names.add("Kiribati");
        names.add("Korea, North");
        names.add("Korea, South");
        names.add("Kuwait");
        names.add("Kyrgyzstan");
        names.add("Laos");
        names.add("Latvia");
        names.add("Lebanon");
        names.add("Lesotho");
        names.add("Liberia");
        names.add("Libya");
        names.add("Liechtenstein");
        names.add("Lithuania");
        names.add("Luxembourg");
        names.add("Macau");
        names.add("Macedonia");
        names.add("Madagascar");
        names.add("Malawi");
        names.add("Malaysia");
        names.add("Maldives");
        names.add("Mali");
        names.add("Malta");
        names.add("Marshall Islands");
        names.add("Martinique");
        names.add("Mauritania");
        names.add("Mauritius");
        names.add("Mayotte");
        names.add("Mexico");
        names.add("Micronesia, Federated States of");
        names.add("Moldova");
        names.add("Monaco");
        names.add("Mongolia");
        names.add("Montserrat");
        names.add("Morocco");
        names.add("Mozambique");
        names.add("Namibia");
        names.add("Nauru");
        names.add("Navassa Island");
        names.add("Nepal");
        names.add("Netherlands");
        names.add("Netherlands Antilles");
        names.add("New Caledonia");
        names.add("New Zealand");
        names.add("Nicaragua");
        names.add("Niger");
        names.add("Nigeria");
        names.add("Niue");
        names.add("Norfolk Island");
        names.add("Northern Mariana Islands");
        names.add("Norway");
        names.add("Oman");
        names.add("Pakistan");
        names.add("Palau");
        names.add("Panama");
        names.add("Papua New Guinea");
        names.add("Paracel Islands");
        names.add("Paraguay");
        names.add("Peru");
        names.add("Philippines");
        names.add("Pitcairn Islands");
        names.add("Poland");
        names.add("Portugal");
        names.add("Puerto Rico");
        names.add("Qatar");
        names.add("Reunion");
        names.add("Romania");
        names.add("Russia");
        names.add("Rwanda");
        names.add("Saint Helena");
        names.add("Saint Kitts and Nevis");
        names.add("Saint Lucia");
        names.add("Saint Pierre and Miquelon");
        names.add("Saint Vincent and the Grenadines");
        names.add("Samoa");
        names.add("San Marino");
        names.add("Sao Tome and Principe");
        names.add("Saudi Arabia");
        names.add("Senegal");
        names.add("Serbia and Montenegro");
        names.add("Seychelles");
        names.add("Sierra Leone");
        names.add("Singapore");
        names.add("Slovakia");
        names.add("Slovenia");
        names.add("Solomon Islands");
        names.add("Somalia");
        names.add("South Africa");
        names.add("South Georgia and the South Sandwich Islands");
        names.add("Spain");
        names.add("Spratly Islands");
        names.add("Sri Lanka");
        names.add("Sudan");
        names.add("Suriname");
        names.add("Svalbard");
        names.add("Swaziland");
        names.add("Sweden");
        names.add("Switzerland");
        names.add("Syria");
        names.add("Taiwan");
        names.add("Tajikistan");
        names.add("Tanzania");
        names.add("Thailand");
        names.add("Timor-Leste");
        names.add("Togo");
        names.add("Tokelau");
        names.add("Tonga");
        names.add("Trinidad and Tobago");
        names.add("Tromelin Island");
        names.add("Tunisia");
        names.add("Turkey");
        names.add("Turkmenistan");
        names.add("Turks and Caicos Islands");
        names.add("Tuvalu");
        names.add("Uganda");
        names.add("Ukraine");
        names.add("United Arab Emirates");
        names.add("United Kingdom");
        names.add("United States");
        names.add("Uruguay");
        names.add("Uzbekistan");
        names.add("Vanuatu");
        names.add("Venezuela");
        names.add("Vietnam");
        names.add("Virgin Islands");
        names.add("Wake Island");
        names.add("Wallis and Futuna");
        names.add("West Bank");
        names.add("Western Sahara");
        names.add("Yemen");
        names.add("Zambia");

    }
}
